[IT-915] Добавлена возможность работать с датой и читать комментарий …
EggheadsSolutions/cakephp-common pull request #21
Opened 2022-12-01 09:09 UTC by Alheor

…к таблице PostgresSql

2022-12-02 14:38 UTC, windstep requested changes

2022-12-02 14:38 UTC, windstep commented on src/EntityBuilder/EntityBuilder.php
> +            $curTblFields[] = ' * @tableComment ' . $tableComment;
Не понимаю немножко логику. У нас есть набор полей, которые мы разбираем. Разве переменная curTblFields не должна содержать уже распаршенные названия полей? Если нет, то на мой взгляд, данная переменная вводит в заблуждение.

2022-12-02 14:38 UTC, windstep commented on src/EntityBuilder/NativeQueryStore/AbstractNativeQueryStore.php
> +        return match (true) {
Не уверен, у нас точно 8-я версия на сервере?

2022-12-02 14:40 UTC, Alheor commented on src/EntityBuilder/NativeQueryStore/AbstractNativeQueryStore.php
> +        return match (true) {
в composer.json   "php": ">=8.0",

2022-12-05 11:12 UTC, denyWhite approved these changes

2022-12-05 12:42 UTC, vovantune commented on test-app-conf/bootstrap.php
> +(new ExceptionTrap(Configure::read('Error')))->register();
Это для новой версии CakePHP?

2022-12-05 13:07 UTC, merged