[IT-1202] Смена места нахождения конфига ProxyClient
EggheadsSolutions/cakephp-common pull request #22
Opened 2022-12-08 15:26 UTC by Alheor

2022-12-08 21:54 UTC, andrew-shelyakov requested changes

2022-12-08 21:54 UTC, andrew-shelyakov commented on test-app-conf/Migrations/20221208175645_DropProxyTable.php
> +    }
Лишняя документация, также использование метода change тут не совсем уместно, drop является irreversible операцией в phinx - лучше написать полноценную логику в up/down.
```suggestion
    /**
     * @inheritDoc
     */
    public function up(): void
    {
        $this->table('proxy_config')->drop()->save();
    }

    /**
     * @inheritDoc
     */
    public function down(): void
    {
        // ...
    }
```

2022-12-12 11:41 UTC, andrew-shelyakov requested changes

2022-12-12 11:41 UTC, andrew-shelyakov commented on test-app-conf/Migrations/20221208175645_DropProxyTable.php
> +                'comment' => 'Прокси',
1. Взаимоисключающие условия, при `'null' => false` не должно быть `'default' => null` -  справедливо для каждого `addColumn` в этой миграции.

2. Также не хватает размерности, она может отличаться от конфигурации к конфигурации - добавь `'length' => 255` для всех `CHAR` колонок.

2022-12-12 12:37 UTC, andrew-shelyakov requested changes

2022-12-12 12:37 UTC, andrew-shelyakov commented on src/Http/ProxyClient.php
> +     * @return array<string, string> ['proxy' => 'string','username' => 'string','password' => 'string']
Корректнее использовать array shapes.
```suggestion
     * @return array{proxy: string, username: string, password: string}
```

2022-12-13 00:18 UTC, andrew-shelyakov approved these changes

2022-12-13 08:12 UTC, vovantune approved these changes

2022-12-13 10:46 UTC, merged