[WB-793] В проект cakephp-common и вынести все необходимые библиотеки для парсинга WB
EggheadsSolutions/cakephp-common pull request #4
Opened 2022-02-15 13:38 UTC by desfpc

2022-02-17 11:30 UTC, vendelev requested changes
А как ты решил проблемы, что UserException не должен отправляться в сентри? 
Так же в сентри не должны отправляться некоторые InternalException?

2022-02-17 11:30 UTC, vendelev commented on phpunit.xml
> +<?xml version="1.0" encoding="UTF-8"?>
А зачем этот файл?

2022-02-17 11:30 UTC, vendelev commented on docker-compose.yml
> +        ports:
Зачем шарить порты?, только проблемы будут при одновременном запуске нескольких проектов

2022-02-17 11:30 UTC, vendelev commented on docker-compose.yml
> +        volumes:
Зачем персистент хранилище для либы, в которой есть только тесты?

2022-02-17 11:30 UTC, vendelev commented on docker-compose.yml
> +        image: eggheads-template-php
Зачем изменил название образа?

2022-02-17 11:30 UTC, vendelev commented on composer.json
> +    "symfony/serializer": "^4.4",
А почему версия 4.4?

2022-02-17 11:30 UTC, vendelev commented on test-app/Template/Error/error500.ctp
> +declare(strict_types=1);
Зачем все эти шаблоны, если мы сейчас не переносим функционал контроллеров?

2022-02-17 11:30 UTC, vendelev commented on test-app/Controller/Chema/EmptyParent.php
> +declare(strict_types=1);
Файлы связанные с функционалом контроллеров предлагю сейчас убрать

2022-02-17 11:30 UTC, vendelev commented on src/ORM/AbstractJsonField.php
> +    public static function createFromArray(array $data, array $context = []): static
Предлагаю этот метод перенести в ConverterTrait (createArrayFromArray), а класс и интерфейс удалить

2022-02-17 11:30 UTC, vendelev commented on src/Lib/Env.php
> + * @method static string getSentryDsn()
не уверен, что все эти методы нужны, например, getSentryOptions больше не требуется. Давай оставим только минимум

2022-02-17 11:30 UTC, vendelev commented on src/Controller/Request/AbstractRequest.php
> +declare(strict_types=1);
Файлы связанные с функционалом контроллеров предлагю сейчас убрать

2022-02-17 11:30 UTC, vendelev commented on config/phinx.php
> +declare(strict_types=1);
А зачем этот файл?

2022-02-18 11:34 UTC, desfpc commented on src/ORM/AbstractJsonField.php
> +    public static function createFromArray(array $data, array $context = []): static
Решили с Владимиром пока указать методы как depricated и выпилить отдельной задачей

2022-02-18 16:06 UTC, vendelev approved these changes

2022-02-20 00:41 UTC, closed without merging